const DEXKEY: any = {
  ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL: {
    title: "Associated Token Account Program",
  },
  "11111111111111111111111111111111": {
    title: "SystemProgram",
  },
  JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4: {
    title: "Jupiter Aggregator v6",
    icon: "https://statics.solscan.io/ex-img/JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4.svg",
    defi_type: "aggregator",
    address: "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
  },
  JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB: {
    title: "Jupiter Aggregator v4",
    icon: "https://statics.solscan.io/ex-img/JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB.svg",
    defi_type: "aggregator",
    address: "JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB",
  },
  CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK: {
    title: "Raydium Concentrated Liquidity",
    icon: "https://statics.solscan.io/ex-img/CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK.png",
    defi_type: "amm",
    address: "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK",
  },
  CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C: {
    title: "Raydium CPMM",
    icon: "https://statics.solscan.io/ex-img/CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK.png",
    defi_type: "amm",
    address: "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C",
  },
  "5quBtoiQqxF9Jv6KYKctB59NT3gtJD2Y65kdnB1Uev3h": {
    title: "Raydium Liquidity Pool AMM",
    icon: "https://statics.solscan.io/ex-img/5quBtoiQqxF9Jv6KYKctB59NT3gtJD2Y65kdnB1Uev3h.png",
    defi_type: "amm",
    address: "5quBtoiQqxF9Jv6KYKctB59NT3gtJD2Y65kdnB1Uev3h",
  },
  "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8": {
    title: "Raydium Liquidity Pool V4",
    icon: "https://statics.solscan.io/ex-img/675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8.png",
    defi_type: "amm",
    address: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
  },
  "27haf8L6oxUeXrHrgEgsexjSY5hbVUWEmvv9Nyxg8vQv": {
    title: "Raydium Liquidity Pool V3",
    icon: "https://statics.solscan.io/ex-img/27haf8L6oxUeXrHrgEgsexjSY5hbVUWEmvv9Nyxg8vQv.png",
    defi_type: "amm",
    address: "27haf8L6oxUeXrHrgEgsexjSY5hbVUWEmvv9Nyxg8vQv",
  },
  RVKd61ztZW9GUwhRbbLoYVRE5Xf1B2tVscKqwZqXgEr: {
    title: "Raydium Liquidity Pool V2",
    icon: "https://statics.solscan.io/ex-img/RVKd61ztZW9GUwhRbbLoYVRE5Xf1B2tVscKqwZqXgEr.png",
    defi_type: "amm",
    address: "RVKd61ztZW9GUwhRbbLoYVRE5Xf1B2tVscKqwZqXgEr",
  },
  routeUGWgWzqBWFcrCfv8tritsqukccJPu3q5GPP3xS: {
    title: "Raydium AMM Routing",
    icon: "https://s2.coinmarketcap.com/static/img/coins/64x64/8526.png",
    defi_type: "amm",
    address: "routeUGWgWzqBWFcrCfv8tritsqukccJPu3q5GPP3xS",
  },
  whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc: {
    title: "Orca Whirlpool",
    icon: "https://statics.solscan.io/ex-img/whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc.svg",
    defi_type: "amm",
    address: "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc",
  },
  "9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP": {
    title: "Orca Swap V2",
    icon: "https://statics.solscan.io/ex-img/9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP.svg",
    defi_type: "amm",
    address: "9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP",
  },
  DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1: {
    title: "Orca Swap V1",
    icon: "https://statics.solscan.io/ex-img/DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1.svg",
    defi_type: "amm",
    address: "DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1",
  },
  LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo: {
    title: "Meteora DLMM Program",
    icon: "https://statics.solscan.io/ex-img/LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo.svg",
    defi_type: "amm",
    address: "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo",
  },
  Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB: {
    title: "Meteora Pools Program",
    icon: "https://statics.solscan.io/ex-img/Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB.svg",
    defi_type: "amm",
    address: "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB",
  },
  PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY: {
    title: "Phoenix",
    icon: "https://statics.solscan.io/ex-img/PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY.svg",
    defi_type: "orderbook",
    address: "PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY",
  },
  "2wT8Yq49kHgDzXuPxZSaeLaH1qbmGXtEyPy64bL7aD3c": {
    title: "Lifinity Swap V2",
    icon: "https://statics.solscan.io/ex-img/2wT8Yq49kHgDzXuPxZSaeLaH1qbmGXtEyPy64bL7aD3c.svg",
    address: "2wT8Yq49kHgDzXuPxZSaeLaH1qbmGXtEyPy64bL7aD3c",
  },
  EewxydAPCCVuNEyrVN68PuSYdQ7wKn27V9Gjeoi8dy3S: {
    title: "Lifinity Swap",
    icon: "https://statics.solscan.io/ex-img/EewxydAPCCVuNEyrVN68PuSYdQ7wKn27V9Gjeoi8dy3S.svg",
    defi_type: "amm",
    address: "EewxydAPCCVuNEyrVN68PuSYdQ7wKn27V9Gjeoi8dy3S",
  },
  SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ: {
    title: "Saber Stable Swap",
    icon: "https://statics.solscan.io/ex-img/SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ.svg",
    defi_type: "amm",
    address: "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ",
  },
  DecZY86MU5Gj7kppfUCEmd4LbXXuyZH1yHaP2NTqdiZB: {
    title: "Saber Decimal Wrapper",
    icon: "https://statics.solscan.io/ex-img/DecZY86MU5Gj7kppfUCEmd4LbXXuyZH1yHaP2NTqdiZB.svg",
    defi_type: "amm",
    address: "DecZY86MU5Gj7kppfUCEmd4LbXXuyZH1yHaP2NTqdiZB",
  },
  HyaB3W9q6XdA5xwpU4XnSZV94htfmbmqJXZcEbRaJutt: {
    title: "Invariant Swap",
    icon: "https://statics.solscan.io/ex-img/HyaB3W9q6XdA5xwpU4XnSZV94htfmbmqJXZcEbRaJutt.svg",
    defi_type: "amm",
    address: "HyaB3W9q6XdA5xwpU4XnSZV94htfmbmqJXZcEbRaJutt",
  },
  stkitrT1Uoy18Dk1fTrgPw8W6MVzoCfYoAFT4MLsmhq: {
    title: "Sanctum Router",
    icon: "https://statics.solscan.io/ex-img/stkitrT1Uoy18Dk1fTrgPw8W6MVzoCfYoAFT4MLsmhq.svg",
    defi_type: "amm",
    address: "stkitrT1Uoy18Dk1fTrgPw8W6MVzoCfYoAFT4MLsmhq",
  },
  "5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx": {
    title: "Sanctum S Controller",
    icon: "https://statics.solscan.io/ex-img/5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx.svg",
    defi_type: "amm",
    address: "5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx",
  },
  opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb: {
    title: "Openbook V2",
    icon: "https://statics.solscan.io/ex-img/opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb.svg",
    defi_type: "orderbook",
    address: "opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb",
  },
  BSwp6bEBihVLdqJRKGgzjcGLHkcTuzmSo1TQkHepzH8p: {
    title: "BonkSwap",
    icon: "https://statics.solscan.io/ex-img/BSwp6bEBihVLdqJRKGgzjcGLHkcTuzmSo1TQkHepzH8p.png",
    defi_type: "amm",
    address: "BSwp6bEBihVLdqJRKGgzjcGLHkcTuzmSo1TQkHepzH8p",
  },
  MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD: {
    title: "Marinade Finance",
    icon: "https://statics.solscan.io/ex-img/MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD.svg",
    defi_type: "amm",
    address: "MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD",
  },
  FLUXubRmkEi2q6K3Y9kBPg9248ggaZVsoSFhtJHSrm1X: {
    title: "Fluxbeam Program",
    icon: "https://statics.solscan.io/ex-img/FLUXubRmkEi2q6K3Y9kBPg9248ggaZVsoSFhtJHSrm1X.png",
    defi_type: "amm",
    address: "FLUXubRmkEi2q6K3Y9kBPg9248ggaZVsoSFhtJHSrm1X",
  },
  GFXsSL5sSaDfNFQUYsHekbWBW1TsFdjDYzACh62tEHxn: {
    title: "GooseFX V2",
    icon: "https://statics.solscan.io/ex-img/GFXsSL5sSaDfNFQUYsHekbWBW1TsFdjDYzACh62tEHxn.svg",
    defi_type: "amm",
    address: "GFXsSL5sSaDfNFQUYsHekbWBW1TsFdjDYzACh62tEHxn",
  },
  MERLuDFBMmsHnsBPZw2sDQZHvXFMwp8EdjudcU2HKky: {
    title: "Mercurial Stable Swap",
    icon: "https://statics.solscan.io/ex-img/MERLuDFBMmsHnsBPZw2sDQZHvXFMwp8EdjudcU2HKky.webp",
    defi_type: "amm",
    address: "MERLuDFBMmsHnsBPZw2sDQZHvXFMwp8EdjudcU2HKky",
  },
  Dooar9JkhdZ7J3LHN3A7YCuoGRUggXhQaG4kijfLGU2j: {
    title: "Dooar Swap",
    icon: "https://statics.solscan.io/ex-img/Dooar9JkhdZ7J3LHN3A7YCuoGRUggXhQaG4kijfLGU2j.webp",
    defi_type: "amm",
    address: "Dooar9JkhdZ7J3LHN3A7YCuoGRUggXhQaG4kijfLGU2j",
  },
  CLMM9tUoggJu2wagPkkqs9eFG4BWhVBZWkP1qv3Sp7tR: {
    title: "Crema Finance",
    icon: "https://statics.solscan.io/ex-img/CLMM9tUoggJu2wagPkkqs9eFG4BWhVBZWkP1qv3Sp7tR.svg",
    defi_type: "amm",
    address: "CLMM9tUoggJu2wagPkkqs9eFG4BWhVBZWkP1qv3Sp7tR",
  },
  DSwpgjMvXhtGn6BsbqmacdBZyfLj6jSWf3HJpdJtmg6N: {
    title: "Dexlab Swap",
    icon: "https://statics.solscan.io/ex-img/DSwpgjMvXhtGn6BsbqmacdBZyfLj6jSWf3HJpdJtmg6N.svg",
    defi_type: "amm",
    address: "DSwpgjMvXhtGn6BsbqmacdBZyfLj6jSWf3HJpdJtmg6N",
  },
  SSwapUtytfBdBn1b9NUGG6foMVPtcWgpRU32HToDUZr: {
    title: "Saros AMM",
    icon: "https://statics.solscan.io/ex-img/SSwapUtytfBdBn1b9NUGG6foMVPtcWgpRU32HToDUZr.svg",
    defi_type: "amm",
    address: "SSwapUtytfBdBn1b9NUGG6foMVPtcWgpRU32HToDUZr",
  },
  CURVGoZn8zycx6FXwwevgBTB2gVvdbGTEpvMJDbgs2t4: {
    title: "Aldrin AMM V2",
    icon: "https://statics.solscan.io/ex-img/AMM55ShdkoGRB5jVYPjWziwk8m5MpwyDgsMWHaMSQWH6.svg",
    defi_type: "amm",
    address: "CURVGoZn8zycx6FXwwevgBTB2gVvdbGTEpvMJDbgs2t4",
  },
  AMM55ShdkoGRB5jVYPjWziwk8m5MpwyDgsMWHaMSQWH6: {
    title: "Aldrin AMM",
    icon: "https://statics.solscan.io/ex-img/AMM55ShdkoGRB5jVYPjWziwk8m5MpwyDgsMWHaMSQWH6.svg",
    defi_type: "amm",
    address: "AMM55ShdkoGRB5jVYPjWziwk8m5MpwyDgsMWHaMSQWH6",
  },
  H8W3ctz92svYg6mkn1UtGfu2aQr2fnUFHM1RhScEtQDt: {
    title: "Cropper Whirlpool",
    icon: "https://statics.solscan.io/ex-img/CTMAxxk34HjKWxQ3QLZK1HpaLXmBveao3ESePXbiyfzh.svg",
    defi_type: "amm",
    address: "H8W3ctz92svYg6mkn1UtGfu2aQr2fnUFHM1RhScEtQDt",
  },
  CTMAxxk34HjKWxQ3QLZK1HpaLXmBveao3ESePXbiyfzh: {
    title: "Cropper Finance",
    icon: "https://statics.solscan.io/ex-img/CTMAxxk34HjKWxQ3QLZK1HpaLXmBveao3ESePXbiyfzh.svg",
    defi_type: "amm",
    address: "CTMAxxk34HjKWxQ3QLZK1HpaLXmBveao3ESePXbiyfzh",
  },
  SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8: {
    title: "Token Swap Program",
    icon: "https://statics.solscan.io/solscan-img/solana_icon.svg",
    defi_type: "amm",
    address: "SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8",
  },
  treaf4wWBBty3fHdyBpo35Mz84M8k3heKXmjmi9vFt5: {
    title: "Helium Treasury Management",
    icon: "https://statics.solscan.io/ex-img/treaf4wWBBty3fHdyBpo35Mz84M8k3heKXmjmi9vFt5.svg",
    defi_type: "amm",
    address: "treaf4wWBBty3fHdyBpo35Mz84M8k3heKXmjmi9vFt5",
  },
  PSwapMdSai8tjrEXcxFeQth87xC4rRsa4VA5mhGhXkP: {
    title: "Penguin Finance",
    icon: "https://statics.solscan.io/ex-img/PSwapMdSai8tjrEXcxFeQth87xC4rRsa4VA5mhGhXkP.png",
    defi_type: "amm",
    address: "PSwapMdSai8tjrEXcxFeQth87xC4rRsa4VA5mhGhXkP",
  },
  SSwpMgqNDsyV7mAgN9ady4bDVu5ySjmmXejXvy2vLt1: {
    title: "Step Finance Swap Program",
    icon: "https://statics.solscan.io/ex-img/SSwpMgqNDsyV7mAgN9ady4bDVu5ySjmmXejXvy2vLt1.svg",
    defi_type: "amm",
    address: "SSwpMgqNDsyV7mAgN9ady4bDVu5ySjmmXejXvy2vLt1",
  },
  MFLQPPPPjNinkdKoy2odNFBhvpY43XtCDZjBwG2fwn5: {
    title: "Marginfi",
    icon: "https://statics.solscan.io/solscan-img/defi_app_marginfi.jpg",
    defi_type: "amm",
    address: "MFLQPPPPjNinkdKoy2odNFBhvpY43XtCDZjBwG2fwn5",
  },
  MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA: {
    title: "Marginfi V2",
    icon: "https://statics.solscan.io/solscan-img/defi_app_marginfi.jpg",
    defi_type: "amm",
    address: "MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA",
  },
  KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD: {
    title: "Kamino Lending",
    icon: "https://cdn.kamino.finance/kamino.svg",
    defi_type: "amm",
    address: "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD",
  },
  "6LtLpnUFNByNXLyCoK9wA2MykKAmQNZKBdY8s47dehDc": {
    title: "Kamino",
    icon: "https://cdn.kamino.finance/kamino.svg",
    defi_type: "amm",
    address: "6LtLpnUFNByNXLyCoK9wA2MykKAmQNZKBdY8s47dehDc",
  },
  FqGg2Y1FNxMiGd51Q6UETixQWkF5fB92MysbYogRJb3P: {
    title: "Hawksight",
    icon: "https://shdw-drive.genesysgo.net/5sh38DtUZ8R7EeJwptc2YeHBaQ2gKvLhdE5c8WZ3ozRk/hawksight.png",
    defi_type: "amm",
    address: "FqGg2Y1FNxMiGd51Q6UETixQWkF5fB92MysbYogRJb3P",
  },
  "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P": {
    title: "Pump.fun",
    icon: "https://statics.solscan.io/solscan-img/defi_app_pumfun.png",
    defi_type: "amm",
    address: "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P",
  },
  MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG: {
    title: "Moonshot",
    icon: "https://statics.solscan.io/solscan-img/moonshot.jpg",
    defi_type: "amm",
    address: "MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG",
  },
  TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA: {
    title: "Token Program",
    icon: "https://statics.solscan.io/solscan-img/solana_icon.svg",
    defi_type: "amm",
    address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  },
  TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb: {
    title: "Token 2022 Program",
    icon: "https://statics.solscan.io/solscan-img/solana_icon.svg",
    defi_type: "amm",
    address: "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  },
  Stake11111111111111111111111111111111111111: {
    title: "Stake Program",
    icon: "https://statics.solscan.io/solscan-img/solana_icon.svg",
    defi_type: "amm",
    address: "Stake11111111111111111111111111111111111111",
  },
  JSW99DKmxNyREQM14SQLDykeBvEUG63TeohrvmofEiw: {
    title: "ApePro Program",
    icon: "https://statics.solscan.io/ex-img/programs/JSW99DKmxNyREQM14SQLDykeBvEUG63TeohrvmofEiw.png",
    defi_type: "amm",
    address: "JSW99DKmxNyREQM14SQLDykeBvEUG63TeohrvmofEiw",
  },
  swapNyd8XiQwJ6ianp9snpu4brUqFxadzvHebnAXjJZ: {
    title: "stabble Stable Swap",
    icon: "https://statics.solscan.io/solscan-img/stabble_icon.png",
    defi_type: "amm",
    address: "swapNyd8XiQwJ6ianp9snpu4brUqFxadzvHebnAXjJZ",
  },
  swapFpHZwjELNnjvThjajtiVmkz3yPQEHjLtka2fwHW: {
    title: "stabble Weight Swap",
    icon: "https://statics.solscan.io/solscan-img/stabble_icon.png",
    defi_type: "amm",
    address: "swapFpHZwjELNnjvThjajtiVmkz3yPQEHjLtka2fwHW",
  },
};

export { DEXKEY };
